CREATE TABLE `dependents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `subscriber_id` int NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `terminated_date` date DEFAULT NULL,
  `person_id` int DEFAULT NULL,
  `plan_id` int DEFAULT NULL,
  `date_of_last_d0120` date DEFAULT NULL,
  `date_of_last_d0140` date DEFAULT NULL,
  `date_of_last_d0150` date DEFAULT NULL,
  `date_of_last_d0180` date DEFAULT NULL,
  `date_of_last_d0210` date DEFAULT NULL,
  `date_of_last_d0272` date DEFAULT NULL,
  `date_of_last_d0274` date DEFAULT NULL,
  `date_of_last_d0330` date DEFAULT NULL,
  `date_of_last_d1110` date DEFAULT NULL,
  `date_of_last_d1120` date DEFAULT NULL,
  `date_of_last_d4341` date DEFAULT NULL,
  `date_of_last_d4342` date DEFAULT NULL,
  `date_of_last_d4910` date DEFAULT NULL,
  `benefits_used` double DEFAULT NULL,
  PRIMARY KEY (`id`,`subscriber_id`),
  KEY `plan_dependent_fk_idx` (`plan_id`),
  KEY `person_dependent_fk_idx` (`person_id`),
  KEY `subscriber_dependent_fk_idx` (`subscriber_id`),
  CONSTRAINT `person_dependent_fk` FOREIGN KEY (`person_id`) REFERENCES `persons` (`ssn`),
  CONSTRAINT `plan_dependent_fk` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`),
  CONSTRAINT `subscriber_dependent_fk` FOREIGN KEY (`subscriber_id`) REFERENCES `subscribers` (`subscriber_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `insurance_company` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `insurance_company_addresses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `street_address` varchar(45) NOT NULL,
  `optional_line_1` varchar(45) DEFAULT NULL,
  `optional_line_2` varchar(45) DEFAULT NULL,
  `city` varchar(45) NOT NULL,
  `state` varchar(2) NOT NULL,
  `zip` int NOT NULL,
  `insurance_company_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `insurance_company_address_fk_idx` (`insurance_company_id`),
  CONSTRAINT `insurance_company_address_fk` FOREIGN KEY (`insurance_company_id`) REFERENCES `insurance_company` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `persons` (
  `ssn` int NOT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `dob` date NOT NULL,
  `sex` char(1) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ssn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `plans` (
  `id` int NOT NULL AUTO_INCREMENT,
  `insurance_company` int DEFAULT NULL,
  `group_number` varchar(255) DEFAULT NULL,
  `group_name` varchar(255) DEFAULT NULL,
  `annual_maximum` double DEFAULT NULL,
  `individual_deductible` double DEFAULT NULL,
  `family_deductible` double DEFAULT NULL,
  `deductible_applies_to_preventive` char(1) DEFAULT NULL,
  `deductible_applies_to_basic` char(1) DEFAULT NULL,
  `deductible_applies_to_major` char(1) DEFAULT NULL,
  `ortho_maximum_coverage` varchar(255) DEFAULT NULL,
  `ortho_age_limit` int NOT NULL,
  `preventive_coverage_percentage` int NOT NULL,
  `basic_coverage_percentage` int NOT NULL,
  `major_coverage_percentage` int NOT NULL,
  `extraction_coverage_percentage` int NOT NULL,
  `crowns_basic_or_major` char(1) DEFAULT NULL,
  `perio_basic_or_major` char(1) DEFAULT NULL,
  `endo_basic_or_major` char(1) DEFAULT NULL,
  `d0220_basic_or_preventive` char(1) DEFAULT NULL,
  `d9110_basic_or_preventive` char(1) DEFAULT NULL,
  `d4381_coverage_percentage` int NOT NULL,
  `implants_coverage_percentage` int NOT NULL,
  `d6058_coverage_percentage` int NOT NULL,
  `d0366_coverage_percentage` int NOT NULL,
  `sealants_coverage_percentage` int NOT NULL,
  `sealants_through_age` int NOT NULL,
  `sealants_frequency` varchar(255) DEFAULT NULL,
  `sealants_coverage_primary_incisors` char(1) DEFAULT NULL,
  `sealants_coverage_primary_molars` char(1) DEFAULT NULL,
  `sealants_coverage_permanent_incisors` char(1) DEFAULT NULL,
  `sealants_coverage_permanent_premolars` char(1) DEFAULT NULL,
  `sealants_coverage_permanent_first_molars` char(1) DEFAULT NULL,
  `sealants_coverage_permanent_second_molars` char(1) DEFAULT NULL,
  `sealants_coverage_permanent_third_molars` char(1) DEFAULT NULL,
  `d1206_coverage_percentage` int NOT NULL,
  `d1206_through_age` int NOT NULL,
  `d1206_frequency` varchar(255) DEFAULT NULL,
  `d7953_coverage_percentage` int NOT NULL,
  `d7953_coverage_with_implant_only` char(1) DEFAULT NULL,
  `d9944_coverage_percentage` int NOT NULL,
  `d9944_frequency` varchar(255) DEFAULT NULL,
  `d9944_coverage_for_bruxism_only` char(1) DEFAULT NULL,
  `posterior_composites_downgraded` char(1) DEFAULT NULL,
  `d0210_frequency` varchar(255) DEFAULT NULL,
  `d0330_frequency` varchar(255) DEFAULT NULL,
  `d0210_d0330_frequency_shared` char(1) DEFAULT NULL,
  `d0120_frequency` varchar(255) DEFAULT NULL,
  `d0140_frequency` varchar(255) DEFAULT NULL,
  `d0150_frequency` varchar(255) DEFAULT NULL,
  `d0180_frequency` varchar(255) DEFAULT NULL,
  `d0120_d0140_frequency_shared` char(1) DEFAULT NULL,
  `d0150_d0140_frequency_shared` char(1) DEFAULT NULL,
  `d0150_d0180_frequency_shared` char(1) DEFAULT NULL,
  `d1110_frequency` varchar(255) DEFAULT NULL,
  `d1120_frequency` varchar(255) DEFAULT NULL,
  `d4910_frequency` varchar(255) DEFAULT NULL,
  `d1110_frequency_increased_diabetes` varchar(255) DEFAULT NULL,
  `d1110_frequency_increased_pregnancy` varchar(255) DEFAULT NULL,
  `fixed_prosthetic_frequency` varchar(255) DEFAULT NULL,
  `removable_prosthetic_frequency` varchar(255) DEFAULT NULL,
  `usual_customary_rates` varchar(255) DEFAULT NULL,
  `missing_tooth_clause` char(1) DEFAULT NULL,
  `waiting_period_preventive_months` int NOT NULL,
  `waiting_period_basic_months` int NOT NULL,
  `waiting_period_major_months` int NOT NULL,
  `d4341_frequency` varchar(255) DEFAULT NULL,
  `d4342_frequency` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `insuranceco_plan_fk_idx` (`insurance_company`),
  CONSTRAINT `insuranceco_plan_fk` FOREIGN KEY (`insurance_company`) REFERENCES `insurance_company` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `subscribers` (
  `subscriber_id` int NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `terminated_date` date DEFAULT NULL,
  `person_id` int DEFAULT NULL,
  `plan_id` int DEFAULT NULL,
  `date_of_last_d0120` date DEFAULT NULL,
  `date_of_last_d0140` date DEFAULT NULL,
  `date_of_last_d0150` date DEFAULT NULL,
  `date_of_last_d0180` date DEFAULT NULL,
  `date_of_last_d0210` date DEFAULT NULL,
  `date_of_last_d0272` date DEFAULT NULL,
  `date_of_last_d0274` date DEFAULT NULL,
  `date_of_last_d0330` date DEFAULT NULL,
  `date_of_last_d1110` date DEFAULT NULL,
  `date_of_last_d1120` date DEFAULT NULL,
  `date_of_last_d4341` date DEFAULT NULL,
  `date_of_last_d4342` date DEFAULT NULL,
  `date_of_last_d4910` date DEFAULT NULL,
  `benefits_used` double DEFAULT NULL,
  PRIMARY KEY (`subscriber_id`),
  KEY `subscriber_plan_fk_idx` (`plan_id`),
  KEY `person_subscriber_fk_idx` (`person_id`),
  CONSTRAINT `person_subscriber_fk` FOREIGN KEY (`person_id`) REFERENCES `persons` (`ssn`),
  CONSTRAINT `subscriber_plan_fk` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;